# Generated by Django 3.0.8 on 2020-08-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(default=None, upload_to='pics'),
        ),
    ]
