# Generated by Django 3.0.8 on 2020-08-08 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200808_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_cover',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_cover',
        ),
    ]
