# Generated by Django 3.0.8 on 2020-08-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200808_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(default='', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_cover',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
